import os
import pytest
from dobby_routes.output import write_annotated, write_optimized, write_complement


def test_write_annotated_creates_file(tmp_path):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    filepath = str(out_dir / "annotated.txt")
    write_annotated(filepath, [("10.0.0.0/8", "CN")])
    assert os.path.exists(filepath)


def test_write_annotated_header(tmp_path):
    filepath = str(tmp_path / "annotated.txt")
    write_annotated(filepath, [])
    content = open(filepath).read()
    assert "# China mainland IP route table (annotated)" in content
    assert "# Generated by dobby-routes on" in content
    assert "UTC" in content


def test_write_annotated_total_routes_count(tmp_path):
    filepath = str(tmp_path / "annotated.txt")
    routes = [("10.0.0.0/8", "CN"), ("192.168.0.0/16", "AS4134/AS4812 China Telecom")]
    write_annotated(filepath, routes)
    content = open(filepath).read()
    assert "# Total routes: 2" in content


def test_write_annotated_body_format(tmp_path):
    filepath = str(tmp_path / "annotated.txt")
    write_annotated(filepath, [("10.0.0.0/8", "CN"), ("172.16.0.0/12", "Unicom")])
    content = open(filepath).read()
    assert "10.0.0.0/8  # CN" in content
    assert "172.16.0.0/12  # Unicom" in content


def test_write_annotated_empty_routes(tmp_path):
    filepath = str(tmp_path / "annotated.txt")
    write_annotated(filepath, [])
    content = open(filepath).read()
    assert "# Total routes: 0" in content


def test_write_optimized_creates_file(tmp_path):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    filepath = str(out_dir / "optimized.txt")
    write_optimized(filepath, ["10.0.0.0/8"])
    assert os.path.exists(filepath)


def test_write_optimized_header(tmp_path):
    filepath = str(tmp_path / "optimized.txt")
    write_optimized(filepath, [])
    content = open(filepath).read()
    assert "# China mainland IP route table (optimized)" in content
    assert "# Generated by dobby-routes on" in content
    assert "UTC" in content


def test_write_optimized_total_routes_count(tmp_path):
    filepath = str(tmp_path / "optimized.txt")
    write_optimized(filepath, ["10.0.0.0/8", "192.168.0.0/16"])
    content = open(filepath).read()
    assert "# Total routes: 2" in content


def test_write_optimized_body_format(tmp_path):
    filepath = str(tmp_path / "optimized.txt")
    write_optimized(filepath, ["10.0.0.0/8", "192.168.0.0/16"])
    content = open(filepath).read()
    assert "10.0.0.0/8\n" in content
    assert "192.168.0.0/16\n" in content


def test_write_optimized_no_annotation(tmp_path):
    filepath = str(tmp_path / "optimized.txt")
    write_optimized(filepath, ["10.0.0.0/8"])
    lines = open(filepath).readlines()
    data_lines = [l for l in lines if not l.startswith("#") and l.strip()]
    assert all("#" not in line for line in data_lines)


def test_write_complement_creates_file(tmp_path):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    filepath = str(out_dir / "complement.txt")
    write_complement(filepath, ["1.0.0.0/8"])
    assert os.path.exists(filepath)


def test_write_complement_header(tmp_path):
    filepath = str(tmp_path / "complement.txt")
    write_complement(filepath, [])
    content = open(filepath).read()
    assert "# Inverse route table (complement of China mainland routes)" in content
    assert "# Generated by dobby-routes on" in content
    assert "UTC" in content


def test_write_complement_total_routes_count(tmp_path):
    filepath = str(tmp_path / "complement.txt")
    write_complement(filepath, ["1.0.0.0/8", "2.0.0.0/8"])
    content = open(filepath).read()
    assert "# Total routes: 2" in content


def test_write_complement_body_format(tmp_path):
    filepath = str(tmp_path / "complement.txt")
    write_complement(filepath, ["1.0.0.0/8", "2.0.0.0/8"])
    content = open(filepath).read()
    assert "1.0.0.0/8\n" in content
    assert "2.0.0.0/8\n" in content


def test_write_functions_use_shared_timestamp(tmp_path):
    ts = "2025-01-01 00:00:00"
    a = str(tmp_path / "a.txt")
    o = str(tmp_path / "o.txt")
    c = str(tmp_path / "c.txt")
    write_annotated(a, [("10.0.0.0/8", "CN")], timestamp=ts)
    write_optimized(o, ["10.0.0.0/8"], timestamp=ts)
    write_complement(c, ["10.0.0.0/8"], timestamp=ts)
    for path in (a, o, c):
        content = open(path).read()
        assert ts in content
