from datetime import datetime, timezone
from typing import Optional


def write_annotated(
    filepath: str,
    annotated_routes: list[tuple[str, str]],
    timestamp: Optional[str] = None,
) -> None:
    if timestamp is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    with open(filepath, "w") as f:
        f.write("# China mainland IP route table (annotated)\n")
        f.write(f"# Generated by dobby-routes on {timestamp} UTC\n")
        f.write(f"# Total routes: {len(annotated_routes)}\n")
        f.write("#\n")
        for cidr, annotation in annotated_routes:
            f.write(f"{cidr}  # {annotation}\n")


def write_optimized(
    filepath: str,
    cidrs: list[str],
    timestamp: Optional[str] = None,
) -> None:
    if timestamp is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    with open(filepath, "w") as f:
        f.write("# China mainland IP route table (optimized)\n")
        f.write(f"# Generated by dobby-routes on {timestamp} UTC\n")
        f.write(f"# Total routes: {len(cidrs)}\n")
        f.write("#\n")
        for cidr in cidrs:
            f.write(f"{cidr}\n")


def write_complement(
    filepath: str,
    cidrs: list[str],
    timestamp: Optional[str] = None,
) -> None:
    if timestamp is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    with open(filepath, "w") as f:
        f.write("# Inverse route table (complement of China mainland routes)\n")
        f.write(f"# Generated by dobby-routes on {timestamp} UTC\n")
        f.write(f"# Total routes: {len(cidrs)}\n")
        f.write("#\n")
        for cidr in cidrs:
            f.write(f"{cidr}\n")
